feat(replica_vol): adding owner id attribute to replica
openebs/mayastor-dependencies pull request #66
Opened 2024-02-13 10:25 UTC by abhilashshetty04

2024-02-20 13:42 UTC, tiagolobocastro commented on apis/io-engine/protobuf/v1/replica.proto
> +  string owner_id = 2; // Owner of the replica.
Might be worth using entity nomenclature which is used by the snapshot already?

```suggestion
message SetReplicaEntityRequest {
  string uuid = 1;  // Uuid of the replica.
  string entity_id = 2; // Id of the entity which owns the replica.
```

2024-02-21 15:48 UTC, tiagolobocastro approved these changes
Please squash

2024-02-21 16:15 UTC, datacore-vvarakantham approved these changes

2024-02-21 16:20 UTC, hrudaya21 commented on apis/io-engine/protobuf/v1/replica.proto
> +  optional string entity_id = 14; // entity which owns the replica, if any
Change the position of the new field. Should be as per its index.

2024-02-21 16:20 UTC, hrudaya21 commented on apis/io-engine/protobuf/v1/replica.proto
> +  optional string entity_id = 14; // entity which owns the replica, if any
Here also position can be changed to last.

2024-02-21 16:46 UTC, hrudaya21 approved these changes

2024-02-21 17:01 UTC, tiagolobocastro requested changes

2024-02-21 17:01 UTC, tiagolobocastro commented on apis/io-engine/protobuf/v1/replica.proto
> +  optional string entity_id = 14; // entity which owns the replica, if any
SHould be 8

2024-02-21 21:42 UTC, tiagolobocastro approved these changes

2024-02-21 21:50 UTC, merged